//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9151
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace acn.ddl {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    [System.Xml.Serialization.XmlRootAttribute("DDL", Namespace="http://www.esta.org/acn/namespace/ddl/2008/", IsNullable=false)]
    public partial class DDLDocument {
        
        private Module itemField;
        
        private string versionField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("behaviorset", typeof(BehaviorSet), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("device", typeof(Device), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("languageset", typeof(LanguageSet), Order=0)]
        public Module Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    [System.Xml.Serialization.XmlRootAttribute("behaviorset", Namespace="http://www.esta.org/acn/namespace/ddl/2008/", IsNullable=false)]
    public partial class BehaviorSet : ConcreteModule {
        
        private BehaviorDefinition[] behaviordefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("behaviordef", Order=0)]
        public BehaviorDefinition[] behaviordef {
            get {
                return this.behaviordefField;
            }
            set {
                this.behaviordefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    [System.Xml.Serialization.XmlRootAttribute("behaviordef", Namespace="http://www.esta.org/acn/namespace/ddl/2008/", IsNullable=false)]
    public partial class BehaviorDefinition : LabeledElement {
        
        private Refines[] refinesField;
        
        private Section[] sectionField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("refines", Order=0)]
        public Refines[] refines {
            get {
                return this.refinesField;
            }
            set {
                this.refinesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("section", Order=1)]
        public Section[] section {
            get {
                return this.sectionField;
            }
            set {
                this.sectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    [System.Xml.Serialization.XmlRootAttribute("refines", Namespace="http://www.esta.org/acn/namespace/ddl/2008/", IsNullable=false)]
    public partial class Refines : BehaviorReference {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Refines))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Behavior))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    public partial class BehaviorReference : IdentifiedNode {
        
        private string setField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string set {
            get {
                return this.setField;
            }
            set {
                this.setField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UseProtocol))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ModuleReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UUIDName))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Module))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConcreteModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LanguageSet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BehaviorSet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Device))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Section))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PropertyPointer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BehaviorReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Refines))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Behavior))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Protocol))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LabeledElement))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Parameter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Language))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BehaviorDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LabeledArrayElement))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Property))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IncludeDevice))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    public abstract partial class IdentifiedNode {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConcreteModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LanguageSet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BehaviorSet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Device))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    public abstract partial class Module : IdentifiedNode {
        
        private UUIDName[] uUIDnameField;
        
        private Parameter[] parameterField;
        
        private Label labelField;
        
        private ModuleReference[] alternateforField;
        
        private ModuleReference[] extendsField;
        
        private string uUIDField;
        
        private string providerField;
        
        private string dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UUIDname", Order=0)]
        public UUIDName[] UUIDname {
            get {
                return this.uUIDnameField;
            }
            set {
                this.uUIDnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameter", Order=1)]
        public Parameter[] parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Label label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("alternatefor", Order=3)]
        public ModuleReference[] alternatefor {
            get {
                return this.alternateforField;
            }
            set {
                this.alternateforField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("extends", Order=4)]
        public ModuleReference[] extends {
            get {
                return this.extendsField;
            }
            set {
                this.extendsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string provider {
            get {
                return this.providerField;
            }
            set {
                this.providerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    [System.Xml.Serialization.XmlRootAttribute("UUIDname", Namespace="http://www.esta.org/acn/namespace/ddl/2008/", IsNullable=false)]
    public partial class UUIDName : IdentifiedNode {
        
        private string uUIDField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    [System.Xml.Serialization.XmlRootAttribute("parameter", Namespace="http://www.esta.org/acn/namespace/ddl/2008/", IsNullable=false)]
    public partial class Parameter : LabeledElement {
        
        private IdentifiedLeafNode[] itemsField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("choice", typeof(ParameterChoice), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("maxinclusive", typeof(MaxInclusive), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("mininclusive", typeof(MinInclusive), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("refinement", typeof(ParameterRefinement), Order=0)]
        public IdentifiedLeafNode[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    [System.Xml.Serialization.XmlRootAttribute("choice", Namespace="http://www.esta.org/acn/namespace/ddl/2008/", IsNullable=false)]
    public partial class ParameterChoice : IdentifiedLeafNode {
        
        private string choiceparamnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("choice.paramname", DataType="NCName")]
        public string choiceparamname {
            get {
                return this.choiceparamnameField;
            }
            set {
                this.choiceparamnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Value))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(String))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetParameter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ParameterRefinement))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ParameterChoice))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Paragraph))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MinInclusive))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MaxInclusive))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Label))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    [System.Xml.Serialization.XmlRootAttribute("hd", Namespace="http://www.esta.org/acn/namespace/ddl/2008/", IsNullable=false)]
    public partial class IdentifiedLeafNode {
        
        private string idField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    [System.Xml.Serialization.XmlRootAttribute("maxinclusive", Namespace="http://www.esta.org/acn/namespace/ddl/2008/", IsNullable=false)]
    public partial class MaxInclusive : IdentifiedLeafNode {
        
        private string maxinclusiveparamnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("maxinclusive.paramname", DataType="NCName")]
        public string maxinclusiveparamname {
            get {
                return this.maxinclusiveparamnameField;
            }
            set {
                this.maxinclusiveparamnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    [System.Xml.Serialization.XmlRootAttribute("mininclusive", Namespace="http://www.esta.org/acn/namespace/ddl/2008/", IsNullable=false)]
    public partial class MinInclusive : IdentifiedLeafNode {
        
        private string mininclusiveparamnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("mininclusive.paramname", DataType="NCName")]
        public string mininclusiveparamname {
            get {
                return this.mininclusiveparamnameField;
            }
            set {
                this.mininclusiveparamnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    [System.Xml.Serialization.XmlRootAttribute("refinement", Namespace="http://www.esta.org/acn/namespace/ddl/2008/", IsNullable=false)]
    public partial class ParameterRefinement : IdentifiedLeafNode {
        
        private string refinementparamnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("refinement.paramname", DataType="NCName")]
        public string refinementparamname {
            get {
                return this.refinementparamnameField;
            }
            set {
                this.refinementparamnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Parameter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Language))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BehaviorDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LabeledArrayElement))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Property))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IncludeDevice))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    public abstract partial class LabeledElement : IdentifiedNode {
        
        private Label labelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Label label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    [System.Xml.Serialization.XmlRootAttribute("label", Namespace="http://www.esta.org/acn/namespace/ddl/2008/", IsNullable=false)]
    public partial class Label : IdentifiedLeafNode {
        
        private string labelparamnameField;
        
        private string setField;
        
        private string setparamnameField;
        
        private string keyField;
        
        private string keyparamnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("label.paramname", DataType="NCName")]
        public string labelparamname {
            get {
                return this.labelparamnameField;
            }
            set {
                this.labelparamnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string set {
            get {
                return this.setField;
            }
            set {
                this.setField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("set.paramname", DataType="NCName")]
        public string setparamname {
            get {
                return this.setparamnameField;
            }
            set {
                this.setparamnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("key.paramname", DataType="NCName")]
        public string keyparamname {
            get {
                return this.keyparamnameField;
            }
            set {
                this.keyparamnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Property))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IncludeDevice))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    public partial class LabeledArrayElement : LabeledElement {
        
        private string arrayField;
        
        private string arrayparamnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string array {
            get {
                return this.arrayField;
            }
            set {
                this.arrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("array.paramname", DataType="NCName")]
        public string arrayparamname {
            get {
                return this.arrayparamnameField;
            }
            set {
                this.arrayparamnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    [System.Xml.Serialization.XmlRootAttribute("alternatefor", Namespace="http://www.esta.org/acn/namespace/ddl/2008/", IsNullable=false)]
    public partial class ModuleReference : IdentifiedNode {
        
        private string uUIDField;
        
        private string uUIDparamnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("UUID.paramname", DataType="NCName")]
        public string UUIDparamname {
            get {
                return this.uUIDparamnameField;
            }
            set {
                this.uUIDparamnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LanguageSet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BehaviorSet))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    public abstract partial class ConcreteModule : Module {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    [System.Xml.Serialization.XmlRootAttribute("section", Namespace="http://www.esta.org/acn/namespace/ddl/2008/", IsNullable=false)]
    public partial class Section : IdentifiedNode {
        
        private IdentifiedLeafNode hdField;
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IdentifiedLeafNode hd {
            get {
                return this.hdField;
            }
            set {
                this.hdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("p", typeof(Paragraph), Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("section", typeof(Section), Order=1)]
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/1999/xhtml", Order=1)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    [System.Xml.Serialization.XmlRootAttribute("p", Namespace="http://www.esta.org/acn/namespace/ddl/2008/", IsNullable=false)]
    public partial class Paragraph : IdentifiedLeafNode {
        
        private string spaceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string space {
            get {
                return this.spaceField;
            }
            set {
                this.spaceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    [System.Xml.Serialization.XmlRootAttribute("device", Namespace="http://www.esta.org/acn/namespace/ddl/2008/", IsNullable=false)]
    public partial class Device : Module {
        
        private UseProtocol[] useprotocolField;
        
        private IdentifiedNode[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("useprotocol", Order=0)]
        public UseProtocol[] useprotocol {
            get {
                return this.useprotocolField;
            }
            set {
                this.useprotocolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("includedev", typeof(IncludeDevice), Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("property", typeof(Property), Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("propertypointer", typeof(PropertyPointer), Order=1)]
        public IdentifiedNode[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    [System.Xml.Serialization.XmlRootAttribute("useprotocol", Namespace="http://www.esta.org/acn/namespace/ddl/2008/", IsNullable=false)]
    public partial class UseProtocol : IdentifiedNode {
        
        private string nameField;
        
        private string nameparamnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("name.paramname", DataType="NCName")]
        public string nameparamname {
            get {
                return this.nameparamnameField;
            }
            set {
                this.nameparamnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    [System.Xml.Serialization.XmlRootAttribute("includedev", Namespace="http://www.esta.org/acn/namespace/ddl/2008/", IsNullable=false)]
    public partial class IncludeDevice : LabeledArrayElement {
        
        private Protocol[] protocolField;
        
        private SetParameter[] setparamField;
        
        private string uUIDField;
        
        private string uUIDparamnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("protocol", Order=0)]
        public Protocol[] protocol {
            get {
                return this.protocolField;
            }
            set {
                this.protocolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("setparam", Order=1)]
        public SetParameter[] setparam {
            get {
                return this.setparamField;
            }
            set {
                this.setparamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("UUID.paramname", DataType="NCName")]
        public string UUIDparamname {
            get {
                return this.uUIDparamnameField;
            }
            set {
                this.uUIDparamnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    [System.Xml.Serialization.XmlRootAttribute("protocol", Namespace="http://www.esta.org/acn/namespace/ddl/2008/", IsNullable=false)]
    public partial class Protocol : IdentifiedNode {
        
        private System.Xml.XmlElement[] anyField;
        
        private string nameField;
        
        private string nameparamnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("name.paramname", DataType="NCName")]
        public string nameparamname {
            get {
                return this.nameparamnameField;
            }
            set {
                this.nameparamnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    [System.Xml.Serialization.XmlRootAttribute("setparam", Namespace="http://www.esta.org/acn/namespace/ddl/2008/", IsNullable=false)]
    public partial class SetParameter : IdentifiedLeafNode {
        
        private string nameField;
        
        private string setparamparamnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("setparam.paramname", DataType="NCName")]
        public string setparamparamname {
            get {
                return this.setparamparamnameField;
            }
            set {
                this.setparamparamnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    [System.Xml.Serialization.XmlRootAttribute("property", Namespace="http://www.esta.org/acn/namespace/ddl/2008/", IsNullable=false)]
    public partial class Property : LabeledArrayElement {
        
        private Behavior[] behaviorField;
        
        private Protocol[] protocolField;
        
        private Value[] valueField;
        
        private IdentifiedNode[] itemsField;
        
        private PropertyValueType valuetypeField;
        
        private string valuetypeparamnameField;
        
        private PropertyShareDefine sharedefineField;
        
        private string sharedefineparamnameField;
        
        public Property() {
            this.sharedefineField = PropertyShareDefine.@false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("behavior", Order=0)]
        public Behavior[] behavior {
            get {
                return this.behaviorField;
            }
            set {
                this.behaviorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("protocol", Order=1)]
        public Protocol[] protocol {
            get {
                return this.protocolField;
            }
            set {
                this.protocolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value", Order=2)]
        public Value[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("includedev", typeof(IncludeDevice), Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("property", typeof(Property), Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("propertypointer", typeof(PropertyPointer), Order=3)]
        public IdentifiedNode[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PropertyValueType valuetype {
            get {
                return this.valuetypeField;
            }
            set {
                this.valuetypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("valuetype.paramname", DataType="NCName")]
        public string valuetypeparamname {
            get {
                return this.valuetypeparamnameField;
            }
            set {
                this.valuetypeparamnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(PropertyShareDefine.@false)]
        public PropertyShareDefine sharedefine {
            get {
                return this.sharedefineField;
            }
            set {
                this.sharedefineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("sharedefine.paramname", DataType="NCName")]
        public string sharedefineparamname {
            get {
                return this.sharedefineparamnameField;
            }
            set {
                this.sharedefineparamnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    [System.Xml.Serialization.XmlRootAttribute("behavior", Namespace="http://www.esta.org/acn/namespace/ddl/2008/", IsNullable=false)]
    public partial class Behavior : BehaviorReference {
        
        private string setparamnameField;
        
        private string nameparamnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("set.paramname", DataType="NCName")]
        public string setparamname {
            get {
                return this.setparamnameField;
            }
            set {
                this.setparamnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("name.paramname", DataType="NCName")]
        public string nameparamname {
            get {
                return this.nameparamnameField;
            }
            set {
                this.nameparamnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    [System.Xml.Serialization.XmlRootAttribute("value", Namespace="http://www.esta.org/acn/namespace/ddl/2008/", IsNullable=false)]
    public partial class Value : IdentifiedLeafNode {
        
        private string valueparamnameField;
        
        private ValueDataType typeField;
        
        private string typeparamnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("value.paramname", DataType="NCName")]
        public string valueparamname {
            get {
                return this.valueparamnameField;
            }
            set {
                this.valueparamnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueDataType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("type.paramname", DataType="NCName")]
        public string typeparamname {
            get {
                return this.typeparamnameField;
            }
            set {
                this.typeparamnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    public enum ValueDataType {
        
        /// <remarks/>
        @uint,
        
        /// <remarks/>
        sint,
        
        /// <remarks/>
        @float,
        
        /// <remarks/>
        @string,
        
        /// <remarks/>
        @object,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    [System.Xml.Serialization.XmlRootAttribute("propertypointer", Namespace="http://www.esta.org/acn/namespace/ddl/2008/", IsNullable=false)]
    public partial class PropertyPointer : IdentifiedNode {
        
        private string refField;
        
        private string refparamnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("ref.paramname", DataType="NCName")]
        public string refparamname {
            get {
                return this.refparamnameField;
            }
            set {
                this.refparamnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    public enum PropertyValueType {
        
        /// <remarks/>
        NULL,
        
        /// <remarks/>
        immediate,
        
        /// <remarks/>
        implied,
        
        /// <remarks/>
        network,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    public enum PropertyShareDefine {
        
        /// <remarks/>
        @false,
        
        /// <remarks/>
        @true,
        
        /// <remarks/>
        arraycommon,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    [System.Xml.Serialization.XmlRootAttribute("languageset", Namespace="http://www.esta.org/acn/namespace/ddl/2008/", IsNullable=false)]
    public partial class LanguageSet : ConcreteModule {
        
        private Language[] languageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("language", Order=0)]
        public Language[] language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    [System.Xml.Serialization.XmlRootAttribute("language", Namespace="http://www.esta.org/acn/namespace/ddl/2008/", IsNullable=false)]
    public partial class Language : LabeledElement {
        
        private String[] stringField;
        
        private string langField;
        
        private string altlangField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("string", Order=0)]
        public String[] @string {
            get {
                return this.stringField;
            }
            set {
                this.stringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string altlang {
            get {
                return this.altlangField;
            }
            set {
                this.altlangField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esta.org/acn/namespace/ddl/2008/")]
    [System.Xml.Serialization.XmlRootAttribute("string", Namespace="http://www.esta.org/acn/namespace/ddl/2008/", IsNullable=false)]
    public partial class String : IdentifiedLeafNode {
        
        private string keyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
    }
}
